name = "discord"
type = "javascript"
workers_dev = true

route = ""
account_id = ""
zone_id = ""

[vars]
PUBLICKEY = "<DISCORD PUBLIC KEY>"
CLIENT_ID = "<DISCORD CLIENT ID>"
# CLIENT_SECRET ~> wrangler secret put CLIENT_SECRET

[[kv_namespaces]]
binding = "ANIMALS"
preview_id = "<KV NAMESPACE ID>"
id = "<KV NAMESPACE ID>"
